//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storefront.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LastNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LastNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Storefront.Resources.LastNames", typeof(LastNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shafferman.
        /// </summary>
        internal static string LastName1 {
            get {
                return ResourceManager.GetString("LastName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bendt.
        /// </summary>
        internal static string LastName10 {
            get {
                return ResourceManager.GetString("LastName10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheat.
        /// </summary>
        internal static string LastName11 {
            get {
                return ResourceManager.GetString("LastName11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smith.
        /// </summary>
        internal static string LastName12 {
            get {
                return ResourceManager.GetString("LastName12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crout.
        /// </summary>
        internal static string LastName2 {
            get {
                return ResourceManager.GetString("LastName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        internal static string LastName3 {
            get {
                return ResourceManager.GetString("LastName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campbell.
        /// </summary>
        internal static string LastName4 {
            get {
                return ResourceManager.GetString("LastName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yochim.
        /// </summary>
        internal static string LastName5 {
            get {
                return ResourceManager.GetString("LastName5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steiner.
        /// </summary>
        internal static string LastName6 {
            get {
                return ResourceManager.GetString("LastName6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feltovich.
        /// </summary>
        internal static string LastName7 {
            get {
                return ResourceManager.GetString("LastName7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gladitz.
        /// </summary>
        internal static string LastName8 {
            get {
                return ResourceManager.GetString("LastName8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deas.
        /// </summary>
        internal static string LastName9 {
            get {
                return ResourceManager.GetString("LastName9", resourceCulture);
            }
        }
    }
}
