//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storefront.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Names {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Names() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Storefront.Resources.Names", typeof(Names).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shane.
        /// </summary>
        internal static string Name1 {
            get {
                return ResourceManager.GetString("Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sara.
        /// </summary>
        internal static string Name10 {
            get {
                return ResourceManager.GetString("Name10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eric.
        /// </summary>
        internal static string Name11 {
            get {
                return ResourceManager.GetString("Name11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christopher.
        /// </summary>
        internal static string Name12 {
            get {
                return ResourceManager.GetString("Name12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darren.
        /// </summary>
        internal static string Name13 {
            get {
                return ResourceManager.GetString("Name13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheri.
        /// </summary>
        internal static string Name14 {
            get {
                return ResourceManager.GetString("Name14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carol.
        /// </summary>
        internal static string Name15 {
            get {
                return ResourceManager.GetString("Name15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samuel.
        /// </summary>
        internal static string Name16 {
            get {
                return ResourceManager.GetString("Name16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jon.
        /// </summary>
        internal static string Name2 {
            get {
                return ResourceManager.GetString("Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nate.
        /// </summary>
        internal static string Name3 {
            get {
                return ResourceManager.GetString("Name3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matthew.
        /// </summary>
        internal static string Name4 {
            get {
                return ResourceManager.GetString("Name4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alexander.
        /// </summary>
        internal static string Name5 {
            get {
                return ResourceManager.GetString("Name5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robert.
        /// </summary>
        internal static string Name6 {
            get {
                return ResourceManager.GetString("Name6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ronald.
        /// </summary>
        internal static string Name7 {
            get {
                return ResourceManager.GetString("Name7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tammy.
        /// </summary>
        internal static string Name8 {
            get {
                return ResourceManager.GetString("Name8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeffrey.
        /// </summary>
        internal static string Name9 {
            get {
                return ResourceManager.GetString("Name9", resourceCulture);
            }
        }
    }
}
